### PR TITLE
error fix

### PR DESCRIPTION
**Pull request by SADASHIMA**
Fixed a failed test to succeed.
Fixed an issue where PolygonSeries was not displayed correctly in ExampleBrowser. 
Fixed for errors from the IDE.

### CODE REVIEW

**Comment by VisualMelon** [comment]
Thank you!

**Comment by VisualMelon** [comment]
Are you OK with being added to the contributors list? That's required for this to be merged into OxyPlot proper

**Comment by SADASHIMA** [comment]
Yes, I am okay with being added.

**Comment by VisualMelon** [comment]
Cool, feel free to open another PR adding yourself, or otherwise let me know how you want to be listed (see https://github.com/VisualMelon/oxyplot/blob/develop/CONTRIBUTORS for examples, but can be pretty much be anything you want) and I'll make sure it gets added

**Pull request merged**
